/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.c
 #	source generated by 4D Plugin Wizard
 #	Project : skypekit
 #	author : miyako
 #	2012/12/15
 #
 # --------------------------------------------------------------------------------*/

#include "4DPluginAPI.h"
#include "4DPlugin.h"

#include "skype-embedded_2.h"
#include "pem.h"//	SKYPEKIT_PEM (the developer key) is defined in this file

#include "functions_desk.h"
#include "functions_runt.h"

#include <time.h>

void PluginMain(int32_t selector, PA_PluginParameters params)
{
	try
	{
		int32_t pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (int32_t pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{
			
		case kDeinitPlugin:
		case kServerDeinitPlugin:
			SKDisconnect();
			break;			
			// --- Desktop API
			
		case 1 :
			SKYPE_DESKTOP_Connect(pResult, pParams);
			break;
			
		case 2 :
			SKYPE_DESKTOP_Send_command(pResult, pParams);
			break;
			
		case 3 :
			SKYPE_DESKTOP_Disconnect(pResult, pParams);
			break;
			
		case 4 :
			SKYPE_DESKTOP_Is_connected(pResult, pParams);
			break;
			
		case 5 :
			SKYPE_DESKTOP_Get_messages(pResult, pParams);
			break;
			
			// --- Desktop
			
		case 6 :
			SKYPE_DESKTOP_LAUNCH(pResult, pParams);
			break;
			
		case 7 :
			SKYPE_DESKTOP_Get_id(pResult, pParams);
			break;
			
		case 8 :
			SKYPE_DESKTOP_TERMINATE(pResult, pParams);
			break;
			
			// --- Runtime
			
		case 9 :
			SKYPE_RUNTIME_LAUNCH(pResult, pParams);
			break;
			
		case 10 :
			SKYPE_RUNTIME_Get_id(pResult, pParams);
			break;
			
		case 11 :
			SKYPE_RUNTIME_TERMINATE(pResult, pParams);
			break;
			
	}
}